In [1]:
import pandas as pd


pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv('../Data/raw/Telco-Customer-Churn.csv')

In [4]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

### Processing to do to data

## Informations sur les clients
Genre : Homme ou femme. <br>
SeniorCitizen : Le client est-il un senior ? (1 = Oui, 0 = Non).<br>
Partner : Le client a-t-il un partenaire ? (Oui, Non).<br>
Dependents : Le client a-t-il des personnes à charge ? (Oui, Non).<br>
Tenure : Nombre de mois d’ancienneté du client dans l’entreprise.<br>

## Services souscrits
PhoneService : Le client possède-t-il un service téléphonique ? (Oui, Non).<br>
MultipleLines : Le client a-t-il plusieurs lignes téléphoniques ? (Oui, Non, Pas de service téléphonique).<br>
InternetService : Fournisseur d’accès à Internet du client (DSL, Fibre optique, Aucun).<br>
OnlineSecurity : Le client possède-t-il un service de sécurité en ligne ? (Oui, Non, Pas de service Internet).<br>
OnlineBackup : Le client possède-t-il une sauvegarde en ligne ? (Oui, Non, Pas de service Internet).<br>
DeviceProtection : Le client possède-t-il une protection des appareils ? (Oui, Non, Pas de service Internet).<br>
TechSupport : Le client a-t-il un support technique ? (Oui, Non, Pas de service Internet).<br>
StreamingTV : Le client possède-t-il un service de streaming TV ? (Oui, Non, Pas de service Internet).<br>
StreamingMovies : Le client possède-t-il un service de streaming de films ? (Oui, Non, Pas de service Internet).<br>

## Informations contractuelles
Contract : Type de contrat du client (Mensuel, Un an, Deux ans).<br>
PaperlessBilling : Le client utilise-t-il la facturation électronique ? (Oui, Non).<br>
PaymentMethod : Méthode de paiement du client (Prélèvement automatique bancaire, Carte de crédit automatique, Chèque électronique,<br> Chèque envoyé).<br>

## Facturation et résiliation
MonthlyCharges : Montant facturé mensuellement.<br>
TotalCharges : Montant total facturé.<br>
Churn : Le client a-t-il résilié son abonnement ? (Oui, Non).<br>

In [5]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [6]:
for col in df.columns:
    print(col)
    print(df[col].unique())

customerID
['7590-VHVEG' '5575-GNVDE' '3668-QPYBK' ... '4801-JZAZL' '8361-LTMKD'
 '3186-AJIEK']
gender
['Female' 'Male']
SeniorCitizen
[0 1]
Partner
['Yes' 'No']
Dependents
['No' 'Yes']
tenure
[ 1 34  2 45  8 22 10 28 62 13 16 58 49 25 69 52 71 21 12 30 47 72 17 27
  5 46 11 70 63 43 15 60 18 66  9  3 31 50 64 56  7 42 35 48 29 65 38 68
 32 55 37 36 41  6  4 33 67 23 57 61 14 20 53 40 59 24 44 19 54 51 26  0
 39]
PhoneService
['No' 'Yes']
MultipleLines
['No phone service' 'No' 'Yes']
InternetService
['DSL' 'Fiber optic' 'No']
OnlineSecurity
['No' 'Yes' 'No internet service']
OnlineBackup
['Yes' 'No' 'No internet service']
DeviceProtection
['No' 'Yes' 'No internet service']
TechSupport
['No' 'Yes' 'No internet service']
StreamingTV
['No' 'Yes' 'No internet service']
StreamingMovies
['No' 'Yes' 'No internet service']
Contract
['Month-to-month' 'One year' 'Two year']
PaperlessBilling
['Yes' 'No']
PaymentMethod
['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
MonthlyCharges
[29.85 56.95 53.85 ... 63.1  44.2  78.7 ]
TotalCharges
['29.85' '1889.5' '108.15' ... '346.45' '306.6' '6844.5']
Churn
['No' 'Yes']

In [7]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors='coerce')
# df['TotalCharges'] = df['TotalCharges'].fillna(df['MonthlyCharges'])

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [15]:
# replacing "no phone sercice" with "no" in MultipleLines column
df["MultipleLines"] = df["MultipleLines"].replace("No phone service", "No")

In [16]:
df["InternetService"].unique()

array(['DSL', 'Fiber optic', 'No'], dtype=object)

In [17]:
for col in df.columns[9:15]:
    df[col] = df[col].replace("No internet service", "No")

In [18]:
# Application de one hot encoding
df_encoded = pd.get_dummies(df, columns=['InternetService'])

In [19]:
# Application de one hot encoding
df_encoded = pd.get_dummies(df_encoded, columns=['Contract'])

In [20]:
df["PaymentMethod"].unique()

array(['Electronic check', 'Mailed check', 'Bank transfer (automatic)',
       'Credit card (automatic)'], dtype=object)

In [21]:
df_encoded = pd.get_dummies(df_encoded, columns=['PaymentMethod'])

In [22]:
df_encoded

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,InternetService_DSL,InternetService_Fiber optic,InternetService_No,Contract_Month-to-month,Contract_One year,Contract_Two year,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,7590-VHVEG,Female,0,Yes,No,1,No,No,No,Yes,No,No,No,No,Yes,29.85,29.85,No,True,False,False,True,False,False,False,False,True,False
1,5575-GNVDE,Male,0,No,No,34,Yes,No,Yes,No,Yes,No,No,No,No,56.95,1889.50,No,True,False,False,False,True,False,False,False,False,True
2,3668-QPYBK,Male,0,No,No,2,Yes,No,Yes,Yes,No,No,No,No,Yes,53.85,108.15,Yes,True,False,False,True,False,False,False,False,False,True
3,7795-CFOCW,Male,0,No,No,45,No,No,Yes,No,Yes,Yes,No,No,No,42.30,1840.75,No,True,False,False,False,True,False,True,False,False,False
4,9237-HQITU,Female,0,No,No,2,Yes,No,No,No,No,No,No,No,Yes,70.70,151.65,Yes,False,True,False,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,84.80,1990.50,No,True,False,False,False,True,False,False,False,False,True
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,No,Yes,Yes,No,Yes,Yes,Yes,103.20,7362.90,No,False,True,False,False,True,False,False,True,False,False
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No,Yes,No,No,No,No,No,Yes,29.60,346.45,No,True,False,False,True,False,False,False,False,True,False
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,No,No,No,No,No,No,Yes,74.40,306.60,Yes,False,True,False,True,False,False,False,False,False,True
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Yes,No,Yes,Yes,Yes,Yes,Yes,105.65,6844.50,No,False,True,False,False,False,True,True,False,False,False

In [1]:
for col in df_encoded.columns:
    print(col)
    print(df_encoded[col].unique())

NameError: name 'df_encoded' is not defined

In [24]:
df_encoded["gender"] = df_encoded["gender"].map({'Female': 1, 'Male': 0})

In [25]:
df_encoded.columns[18:]

Index(['InternetService_DSL', 'InternetService_Fiber optic',
       'InternetService_No', 'Contract_Month-to-month', 'Contract_One year',
       'Contract_Two year', 'PaymentMethod_Bank transfer (automatic)',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check'],
      dtype='object')

In [26]:
df_encoded["TotalCharges"].isnull().sum()

0

In [27]:
# Convertir les colonnes contenant "Yes" et "No" en type boolean
columns_to_convert = ['Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'PaperlessBilling', 'Churn']
columns_to_convert2 = list(df_encoded.columns[18:])

for col in columns_to_convert:
    df_encoded[col] = df_encoded[col].map({'Yes': 1, 'No': 0})

for col in columns_to_convert2:
    df_encoded[col] = df_encoded[col].map({True: 1, False: 0})

In [28]:
df_encoded.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,InternetService_DSL,InternetService_Fiber optic,InternetService_No,Contract_Month-to-month,Contract_One year,Contract_Two year,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,7590-VHVEG,1,0,1,0,1,0,0,0,1,0,0,0,0,1,29.85,29.85,0,1,0,0,1,0,0,0,0,1,0
1,5575-GNVDE,0,0,0,0,34,1,0,1,0,1,0,0,0,0,56.95,1889.50,0,1,0,0,0,1,0,0,0,0,1
2,3668-QPYBK,0,0,0,0,2,1,0,1,1,0,0,0,0,1,53.85,108.15,1,1,0,0,1,0,0,0,0,0,1
3,7795-CFOCW,0,0,0,0,45,0,0,1,0,1,1,0,0,0,42.30,1840.75,0,1,0,0,0,1,0,1,0,0,0
4,9237-HQITU,1,0,0,0,2,1,0,0,0,0,0,0,0,1,70.70,151.65,1,0,1,0,1,0,0,0,0,1,0

In [36]:
df_encoded.dtypes

customerID                                  object
gender                                       int64
SeniorCitizen                                int64
Partner                                      int64
Dependents                                   int64
tenure                                       int64
PhoneService                                 int64
MultipleLines                                int64
OnlineSecurity                               int64
OnlineBackup                                 int64
DeviceProtection                             int64
TechSupport                                  int64
StreamingTV                                  int64
StreamingMovies                              int64
PaperlessBilling                             int64
MonthlyCharges                             float64
TotalCharges                               float64
InternetService_DSL                          int64
InternetService_Fiber optic                  int64
InternetService_No                           int64
Contract_Month-to-month                      int64
Contract_One year                            int64
Contract_Two year                            int64
PaymentMethod_Bank transfer (automatic)      int64
PaymentMethod_Credit card (automatic)        int64
PaymentMethod_Electronic check               int64
PaymentMethod_Mailed check                   int64
Churn                                        int64
dtype: object

In [37]:
df_encoded.isna().sum()

customerID                                 0
gender                                     0
SeniorCitizen                              0
Partner                                    0
Dependents                                 0
tenure                                     0
PhoneService                               0
MultipleLines                              0
OnlineSecurity                             0
OnlineBackup                               0
DeviceProtection                           0
TechSupport                                0
StreamingTV                                0
StreamingMovies                            0
PaperlessBilling                           0
MonthlyCharges                             0
TotalCharges                               0
InternetService_DSL                        0
InternetService_Fiber optic                0
InternetService_No                         0
Contract_Month-to-month                    0
Contract_One year                          0
Contract_Two year                          0
PaymentMethod_Bank transfer (automatic)    0
PaymentMethod_Credit card (automatic)      0
PaymentMethod_Electronic check             0
PaymentMethod_Mailed check                 0
Churn                                      0
dtype: int64

In [31]:
# Déplacer la colonne 'Churn' vers la fin
churn = df_encoded.pop('Churn')
df_encoded['Churn'] = churn

In [32]:
def Encode(df):
    try:
        df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors='coerce')
        df['TotalCharges'] = df['TotalCharges'].fillna(df['MonthlyCharges'])
        
        # replacing "no phone sercice" with "no" in MultipleLines column
        df["MultipleLines"] = df["MultipleLines"].replace("No phone service", "No")
        for col in df.columns[9:15]:
            df[col] = df[col].replace("No internet service", "No")
            
        # Application de one hot encoding
        df_encoded = pd.get_dummies(df, columns=['InternetService'])
        
        # Application de one hot encoding
        df_encoded = pd.get_dummies(df_encoded, columns=['Contract'])
        df_encoded = pd.get_dummies(df_encoded, columns=['PaymentMethod'])
        df_encoded["gender"] = df_encoded["gender"].map({'Female': 1, 'Male': 0})
        
        # Convertir les colonnes contenant "Yes" et "No" en type boolean
        columns_to_convert = ['Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'PaperlessBilling', 'Churn']
        columns_to_convert2 = list(df_encoded.columns[18:])

        for col in columns_to_convert:
            df_encoded[col] = df_encoded[col].map({'Yes': 1, 'No': 0})

        for col in columns_to_convert2:
            df_encoded[col] = df_encoded[col].map({True: 1, False: 0})

        # Déplacer la colonne 'Churn' vers la fin
        churn = df_encoded.pop('Churn')
        df_encoded['Churn'] = churn
        df_final = df_encoded.iloc[:,1:]
    except:
        return "Error reading the data"
    return df_final

In [33]:
df_test = Encode(df)

In [34]:
df_test.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,PaperlessBilling,MonthlyCharges,TotalCharges,InternetService_DSL,InternetService_Fiber optic,InternetService_No,Contract_Month-to-month,Contract_One year,Contract_Two year,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,Churn
0,1,0,1,0,1,0,0,0,1,0,0,0,0,1,29.85,29.85,1,0,0,1,0,0,0,0,1,0,0
1,0,0,0,0,34,1,0,1,0,1,0,0,0,0,56.95,1889.50,1,0,0,0,1,0,0,0,0,1,0
2,0,0,0,0,2,1,0,1,1,0,0,0,0,1,53.85,108.15,1,0,0,1,0,0,0,0,0,1,1
3,0,0,0,0,45,0,0,1,0,1,1,0,0,0,42.30,1840.75,1,0,0,0,1,0,1,0,0,0,0
4,1,0,0,0,2,1,0,0,0,0,0,0,0,1,70.70,151.65,0,1,0,1,0,0,0,0,1,0,1

In [41]:
df_encoded.iloc[:,1:].to_csv('../Data/processed/Telco-Customer-Churn-Encoded.csv', index=False)